# Generated by Django 4.0 on 2022-01-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_active',
            new_name='active',
        ),
    ]
