# Generated by Django 4.0 on 2022-01-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_is_active_variation_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='active',
            new_name='is_active',
        ),
    ]
